import type { GeneratorConfig, TemplateContribution } from '../core/types.js';

export function javaBackend(config: GeneratorConfig): TemplateContribution {
  const group = 'com.generated.saas';
  const artifact = config.projectName;
  return {
    files: {
      'backend/pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.4.3</version></parent><groupId>${group}</groupId><artifactId>${artifact}</artifactId><properties><java.version>21</java.version></properties><dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency><dependency><groupId>org.postgresql</groupId><artifactId>postgresql</artifactId><scope>runtime</scope></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-security</artifactId></dependency><dependency><groupId>io.jsonwebtoken</groupId><artifactId>jjwt-api</artifactId><version>0.12.6</version></dependency><dependency><groupId>io.jsonwebtoken</groupId><artifactId>jjwt-impl</artifactId><version>0.12.6</version><scope>runtime</scope></dependency><dependency><groupId>io.jsonwebtoken</groupId><artifactId>jjwt-jackson</artifactId><version>0.12.6</version><scope>runtime</scope></dependency></dependencies><build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build></project>\n`,
      'backend/src/main/resources/application.yml':
        'server:\n  port: ${PORT:8080}\nspring:\n  datasource:\n    url: ${DATABASE_URL}\n    username: ${DATABASE_USER:}\n    password: ${DATABASE_PASSWORD:}\n  jpa:\n    hibernate:\n      ddl-auto: update\napp:\n  jwt:\n    secret: ${SESSION_SECRET}\n    issuer: ${JWT_ISSUER}\n    audience: ${JWT_AUDIENCE}\n',
      'backend/src/main/java/com/generated/saas/SaasApplication.java':
        'package com.generated.saas; import org.springframework.boot.*; import org.springframework.boot.autoconfigure.*; @SpringBootApplication public class SaasApplication { public static void main(String[] args){SpringApplication.run(SaasApplication.class,args);} }\n',
      'backend/src/main/java/com/generated/saas/domain/User.java':
        'package com.generated.saas.domain; import jakarta.persistence.*; @Entity @Table(name="users") public class User { @Id public String id; @Column(unique=true,nullable=false) public String email; public String name; public String passwordHash; protected User(){} public User(String id,String email,String name,String hash){this.id=id;this.email=email;this.name=name;this.passwordHash=hash;} }\n',
      'backend/src/main/java/com/generated/saas/repository/UserRepository.java':
        'package com.generated.saas.repository; import java.util.*; import org.springframework.data.jpa.repository.JpaRepository; import com.generated.saas.domain.User; public interface UserRepository extends JpaRepository<User,String>{Optional<User> findByEmail(String email);}\n',
      'backend/src/main/java/com/generated/saas/security/JwtService.java':
        'package com.generated.saas.security; import io.jsonwebtoken.*; import io.jsonwebtoken.security.Keys; import java.nio.charset.StandardCharsets; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; @Service public class JwtService { private final byte[] key; private final String issuer,audience; public JwtService(@Value("${app.jwt.secret}") String s,@Value("${app.jwt.issuer}") String i,@Value("${app.jwt.audience}") String a){key=s.getBytes(StandardCharsets.UTF_8);issuer=i;audience=a;} public String issue(String id){return Jwts.builder().subject(id).issuer(issuer).audience().add(audience).and().expiration(new Date(System.currentTimeMillis()+86400000)).signWith(Keys.hmacShaKeyFor(key)).compact();} public String verify(String token){return Jwts.parser().verifyWith(Keys.hmacShaKeyFor(key)).requireIssuer(issuer).requireAudience(audience).build().parseSignedClaims(token).getPayload().getSubject();} }\n',
      'backend/src/main/java/com/generated/saas/web/AuthController.java':
        'package com.generated.saas.web; import java.util.*; import org.springframework.http.*; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.web.bind.annotation.*; import com.generated.saas.domain.User; import com.generated.saas.repository.UserRepository; import com.generated.saas.security.JwtService; @RestController @RequestMapping("/api/v1/auth") public class AuthController { record Credentials(String email,String password,String name){} private final UserRepository users; private final JwtService jwt; private final BCryptPasswordEncoder passwords=new BCryptPasswordEncoder(); AuthController(UserRepository u,JwtService j){users=u;jwt=j;} @PostMapping("/register") ResponseEntity<?> register(@RequestBody Credentials c){if(c.password()==null||c.password().length()<12)return ResponseEntity.badRequest().body(Map.of("error","Password must be 12 characters"));if(users.findByEmail(c.email()).isPresent())return ResponseEntity.status(409).body(Map.of("error","Email already registered"));var u=users.save(new User(UUID.randomUUID().toString(),c.email().toLowerCase(),c.name(),passwords.encode(c.password())));return ResponseEntity.status(201).body(Map.of("user",Map.of("id",u.id,"email",u.email,"name",u.name),"token",jwt.issue(u.id)));} @PostMapping("/login") ResponseEntity<?> login(@RequestBody Credentials c){var u=users.findByEmail(c.email().toLowerCase()).filter(x->passwords.matches(c.password(),x.passwordHash));return u.<ResponseEntity<?>>map(x->ResponseEntity.ok(Map.of("user",Map.of("id",x.id,"email",x.email,"name",x.name),"token",jwt.issue(x.id)))).orElseGet(()->ResponseEntity.status(401).body(Map.of("error","Invalid credentials")));} }\n',
      'backend/Dockerfile':
        'FROM maven:3.9-eclipse-temurin-21 AS build\nWORKDIR /src\nCOPY pom.xml .\nRUN mvn -q dependency:go-offline\nCOPY src src\nRUN mvn -q package -DskipTests\nFROM eclipse-temurin:21-jre\nCOPY --from=build /src/target/*.jar /app.jar\nENTRYPOINT ["java","-jar","/app.jar"]\n',
      'scripts/deploy-cloud-run-java.sh':
        '#!/usr/bin/env bash\nset -euo pipefail\n: "${PROJECT_ID:?}" "${SERVICE:?}" "${REGION:?}" "${JWT_ISSUER:?}" "${JWT_AUDIENCE:?}"\ngcloud run deploy "$SERVICE" --source backend --region "$REGION" --set-env-vars "JWT_ISSUER=$JWT_ISSUER,JWT_AUDIENCE=$JWT_AUDIENCE" --set-secrets "SESSION_SECRET=session-secret:latest,DATABASE_URL=database-url:latest"\n',
    },
    readmeSections: [
      '## Java API\n\nSpring Boot + Spring Data JPA provides ORM-based persistence; JJWT signs and validates JWTs with required issuer and audience.',
    ],
  };
}
