import { resolve } from 'node:path';
import { openApi } from '../templates/openapi.js';
import { resolveModules } from './modules.js';
import type { EnvironmentVariable, GeneratorConfig } from './types.js';
import { validateConfig } from './validate.js';
import { writeTransaction } from './writer.js';

function envFile(env: EnvironmentVariable[]): string {
  return env
    .map(
      (item) =>
        `# ${item.description}${item.required ? ' (required)' : ''}\n${item.key}=${item.value ?? ''}\n`,
    )
    .join('\n');
}
function readme(config: GeneratorConfig, sections: string[]): string {
  return `# ${config.projectName}\n\nGenerated by create-composable-saas.\n\n## Selected stack\n\n- Backend: ${config.backend}\n- Frontend: ${config.frontend}\n- Database: ${config.database}\n- Storage: ${config.storage}\n- Email: ${config.email}\n- Stripe: ${config.billing ? 'enabled' : 'disabled'}\n- Organizations: ${config.organizations ? 'enabled' : 'disabled'}\n\n${sections.join('\n\n')}\n\n## Security\n\nNever commit the .env file. Use managed identities where supported and set production-only secure cookies.\n`;
}

export async function generateProject(
  config: GeneratorConfig,
  parent = process.cwd(),
): Promise<string> {
  const errors = validateConfig(config);
  if (errors.length) throw new Error(errors.join('\n'));
  const contributions = resolveModules(config).map((module) => module.contribute(config));
  const files: Record<string, string> = {
    '.gitignore': '.env\nnode_modules\ndist\nuploads\n',
    'saas.config.json': JSON.stringify(config, null, 2) + '\n',
    'shared/openapi.yaml': openApi,
  };
  const env: EnvironmentVariable[] = [
    {
      key: 'SESSION_SECRET',
      required: true,
      secret: true,
      description: 'Long random JWT signing secret (use a managed secret in production)',
    },
    {
      key: 'JWT_ISSUER',
      required: true,
      value: 'http://localhost:3000',
      description: 'Expected JWT issuer',
    },
    { key: 'JWT_AUDIENCE', required: true, value: 'web', description: 'Expected JWT audience' },
    {
      key: 'FRONTEND_URL',
      required: false,
      value: 'http://localhost:5173',
      description: 'Allowed browser client origin',
    },
    {
      key: 'VITE_API_URL',
      required: false,
      value: 'http://localhost:3000/api/v1',
      description: 'Frontend API base URL',
    },
  ];
  const sections: string[] = [];
  const dependencies: Record<string, string> = {};
  for (const contribution of contributions) {
    for (const [path, contents] of Object.entries(contribution.files ?? {})) {
      if (files[path]) throw new Error(`Template conflict at ${path}`);
      files[path] = contents;
    }
    Object.assign(dependencies, contribution.dependencies);
    env.push(...(contribution.env ?? []));
    sections.push(...(contribution.readmeSections ?? []));
  }
  if (files['backend/package.json']) {
    const backendPackage = JSON.parse(files['backend/package.json']) as {
      dependencies?: Record<string, string>;
    };
    backendPackage.dependencies = { ...backendPackage.dependencies, ...dependencies };
    files['backend/package.json'] = JSON.stringify(backendPackage, null, 2) + '\n';
  }
  const hasBackend = Object.keys(files).some((path) => path.startsWith('backend/'));
  const hasFrontend = Object.keys(files).some((path) => path.startsWith('frontend/'));
  if (!hasBackend || !hasFrontend)
    throw new Error(
      `The selected stack has no executable ${!hasBackend ? 'backend' : 'frontend'} template. Generation was stopped before writing a configuration-only project.`,
    );
  files['generator.manifest.json'] =
    JSON.stringify(
      { modules: resolveModules(config).map((module) => module.id), dependencies },
      null,
      2,
    ) + '\n';
  files['.env.example'] = envFile([...new Map(env.map((item) => [item.key, item])).values()]);
  files['README.md'] = readme(config, sections);
  const destination = resolve(parent, config.projectName);
  await writeTransaction(destination, files);
  return destination;
}
